### PR TITLE
Production environment needs

### PR DESCRIPTION
**Pull request by saaavsaaa**
conditional : centos 6.5 ; i can't use database in this case

1.don't support to view anything without login
2.when rsyslog output pattern : "/var/log/%PROGRAMNAME%/%Y%m%d.log" then show log can change date and search selected date log

### CODE REVIEW

**Comment by alorbach** [comment]
So you want to use user login stuff without having the userdb system installed or configured? 
I don't know if this is the right way to go. Seems to mae more sense to me to find another way to use the userdb system without mysql.

**Comment by saaavsaaa** [comment]
1,yes,because our loganalyzer will view on the Internet and the content inconvenient for others to see. I haven't VPN. In fact,i can use the resources which only a few directory.
2.I can only use the log file mode.But a single file is too large.So I split the file by date,then I need to be able to read the day before.
This all my code.
My English is too bad, I wish I wrote all the sentences correctly.

**Comment by alorbach** [comment]
Regarding the security issues, it makes more sense to just use apache authentication using .htaccess then adding another user / password access system to loganalyzer. 
(Help here: https://wiki.apache.org/httpd/PasswordBasicAuth)

The changes related to logfile splitting might be interesting.

**Comment by saaavsaaa** [comment]
thanks, i let operations staff to try about this next week.
And the second one? Perhaps, what kind of userdb

**Comment by saaavsaaa** [comment]
i'll remove authentication code

**Comment by saaavsaaa** [comment]
Adjust the indentation to complete

**Comment by alorbach** [comment]
Can you remove the config.php from your commit? It shouldn't be added to the source tree. After that I will review and merge the patch

**Comment by saaavsaaa** [comment]
already removed. Sorry ,these days, occasional I can't access my mail box, just received the mail

**Pull request closed without merging**
